-- Campanhas de frete grátis agendadas por período e produto.
CREATE TABLE IF NOT EXISTS public.promocoes_frete_gratis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id integer REFERENCES public.produtos(id) ON DELETE CASCADE,
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  hora_inicio time NOT NULL DEFAULT '00:00',
  hora_fim time NOT NULL DEFAULT '23:59',
  ativa boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT promocoes_frete_periodo_valido CHECK (data_fim >= data_inicio),
  CONSTRAINT promocoes_frete_datetime_valido
    CHECK (data_fim > data_inicio OR (data_fim = data_inicio AND hora_fim >= hora_inicio))
);

ALTER TABLE public.promocoes_frete_gratis ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS promocoes_frete_select_public ON public.promocoes_frete_gratis;
CREATE POLICY promocoes_frete_select_public
  ON public.promocoes_frete_gratis FOR SELECT TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS promocoes_frete_periodo_idx
  ON public.promocoes_frete_gratis (ativa, data_inicio, data_fim);
